homeassistant:

pi_hole:
  host: 192.168.1.200:9090

# sensor:
#   - platform: pi_hole
#     host: 192.168.1.200:8090
#     monitored_conditions:
#       - ads_blocked_today
#       - ads_percentage_today
#       - dns_queries_today
#       - domains_being_blocked
#       - queries_cached
#       - queries_forwarded
#       - unique_clients
#       - unique_domains